on:
  push:
  workflow_dispatch: ~

jobs:
  homebrew-releaser:
    runs-on: ubuntu-latest
    name: homebrew-releaser
    steps:
      - name: Release my project to my Homebrew tap
        uses: Justintime50/homebrew-releaser@v3
        with:
          homebrew_owner: Justintime50
          homebrew_tap: homebrew-test
          github_token: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          commit_owner: Justintime50
          commit_email: 39606064+Justintime50@users.noreply.github.com
          custom_tarball: muffinscript
          update_readme_table: true
          install: |
            libexec.install "muffin"
            bin.install_symlink libexec/"muffin/muffin" => "muffin"
          test: 'assert_match "Muffin", shell_output("#{bin}/muffin --version")'
          skip_checksum: true
          debug: true
